
env:
   global:
     - CONAN_REFERENCE: "soilcpp/0.1.0"
     - CONAN_USERNAME: "lemiort"
     - CONAN_LOGIN_USERNAME: "lemiort"
     - CONAN_CHANNEL: "developing"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/lemiort/conan-public"

linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:

      - <<: *linux
        env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
