find_path(SOILCPP_INCLUDE_DIR NAMES SOIL.hpp PATHS {CONAN_INCLUDE_DIRS_SOILCPP} NO_CMAKE_FIND_ROOT_PATH)
find_library(SOILCPP_LIBRARY NAMES ${CONAN_LIBS_SOILCPP} PATHS ${CONAN_LIB_DIRS_SOILCPP} NO_CMAKE_FIND_ROOT_PATH)

message(STATUS "** SOILCPP ALREADY FOUND BY CONAN!")
message(STATUS "** FOUND SOIL: ${SOILCPP_LIBRARY}")
message(STATUS "** FOUND SOIL INCLUDE: ${SOILCPP_INCLUDE_DIR}")

set(SOILCPP_FOUND TRUE)
set(SOILCPP_INCLUDE_DIRS ${SOILCPP_INCLUDE_DIR})
set(SOILCPP_LIBRARIES ${SOILCPP_LIBRARY})

mark_as_advanced(SOILCPP_LIBRARY SOILCPP_INCLUDE_DIR)
